#!/bin/sh

################# SendTimeLogger_DOS.sh #################
#
# This shell script allows to put an archive conitaining
# all the data collected by the Time Logger during a 
# RT-MaG model's execution:
#    + TimeLogger.zip
#    |--- TimeLogger_Task0.csv : ';' delimited file with Task0' data
#    |--- ... 
#    |--- TimeLogger_TaskN.csv : ';' delimited file with Task0' data
#    |--- top-output.txt       : text file with the CPU history of each PID (results of the "top" command)
#    |--- README.txt           : text file with instructions to plot these data in MATLAB
#
# USAGE (for the first downloading):
#
# 1) On your Gumstix, type: 
#    wget ftp://overo:gumstix@192.168.137.1/SendTimeLogger_DOS.sh
#              ^      ^          ^
#              |      |          |
#            login  password  server's IP
# 
# 2) Then convert your DOS file to a UNIX file:
#    sed 's/.$//' SendTimeLogger_DOS.sh > SendTimeLogger
#    rm SendTimeLogger_DOS.sh
#
# 3) Make your script exectable:
#    chmod +x SendTimeLogger
#
###############################################

# get the RT-MaG profile data
source ~/RT_MaG_ToolBox/LoadProfile

#tar -zcvf TimeLogger.tar.gz TempTimeLoggerDir
zip -r TimeLogger.zip TimeLogger

ftp -n -v $HOST << EOT
user $USER $PASSWD
prompt
binary
put TimeLogger.zip
bye
EOT

#rm TimeLogger.tar.gz
rm TimeLogger.zip

