#!/bin/sh

~/RT_MaG_ToolBox/RT_MaG_Program/PullFTP libreadline5_5.2-r8.6_armv7a.ipk
~/RT_MaG_ToolBox/RT_MaG_Program/PullFTP inetutils_1.8-r8.6_armv7a.ipk
opkg install libreadline5_5.2-r8.6_armv7a.ipk
opkg install inetutils_1.8-r8.6_armv7a.ipk

